---
# cf. https://www.cockroachlabs.com/docs/v26.2/start-a-local-cluster-in-docker-linux
services:
  # cf. https://www.cockroachlabs.com/docs/v26.2/start-a-local-cluster-in-docker-linux#step-3-start-the-cluster
  roach1:
    image: cockroachdb/cockroach:v26.2.0
    hostname: roach1
    networks:
      - roachnet
    command:
      - start
      - --advertise-addr=roach1:26357
      - --http-addr=roach1:8080
      - --listen-addr=roach1:26357
      - --sql-addr=roach1:26257
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - 26257:26257
      - 8080:8080
    volumes:
      - roach1:/cockroach/cockroach-data
  
  roach2:
    image: cockroachdb/cockroach:v26.2.0
    hostname: roach2
    networks:
      - roachnet
    command:
      - start
      - --advertise-addr=roach2:26357
      - --http-addr=roach2:8081
      - --listen-addr=roach2:26357
      - --sql-addr=roach2:26258
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - 26258:26258
      - 8081:8081
    volumes:
      - roach2:/cockroach/cockroach-data

  roach3:
    image: cockroachdb/cockroach:v26.2.0
    hostname: roach3
    networks:
      - roachnet
    command:
      - start
      - --advertise-addr=roach3:26357
      - --http-addr=roach3:8082
      - --listen-addr=roach3:26357
      - --sql-addr=roach3:26259
      - --insecure
      - --join=roach1:26357,roach2:26357,roach3:26357
    ports:
      - 26259:26259
      - 8082:8082
    volumes:
      - roach3:/cockroach/cockroach-data
  
  init:
    image: cockroachdb/cockroach:v26.2.0
    container_name: roach_init
    networks:
      - roachnet
    command: init --insecure --host=roach1:26357
    depends_on:
      - roach1

# Step1. Create a bridge network に相当
# cf. https://www.cockroachlabs.com/docs/v26.2/start-a-local-cluster-in-docker-linux#step-1-create-a-bridge-network
networks:
  roachnet:
    driver: bridge

# Step2. Create Docker volumes for each cluster node に相当
# cf. https://www.cockroachlabs.com/docs/v26.2/start-a-local-cluster-in-docker-linux#step-2-create-docker-volumes-for-each-cluster-node
volumes:
  roach1:
  roach2:
  roach3:
